version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mo2005hamod@
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  admin-app:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: course-admin-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=CourseManagement;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=mo2005hamod@
    depends_on:
      - sqlserver

  public-app:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: course-public-app
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=CourseManagement;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=mo2005hamod@
    depends_on:
      - sqlserver

volumes:
  mssql-data:
